# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83f8813a60f9c40f816b85fa84bc21b11b67e12b43bfd98677b70c6466a09de62f5b083623ab584900154290b219e0fec9321d8d366c1e0847841d2721285a09

test:
  secret_key_base: 3bc32550b5a144e17095efffe8601b6120563f33d1d5282737ec778988314ea58e2e1fdea30e12e69ee6c6159fec0897f6494a3a0bd9c10abc31c1ec8bd2884c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
